### ISSUE TITLE
In the output file fields are empty

### ISSUE THREAD

**Issue by nagenaga** [dfesenko/zoominfo_scraper#1]
Hi, it worked fine when I executed the code. But the issue is that empty fields or results were not generated in the individual company output file. What is the reason?

**Comment by dfesenko** [comment]
Hi, I'm not sure because this project is not active at the moment. Zoominfo can implement additional anti-scraping techniques or just change the structure of its pages. Anyway, to get proper results the scraper requires some maintenance from time to time, which I cannot do at the moment.
